In [2]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [3]:
import random
random.seed(5)

In [4]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data
Y = iris.target

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
from sklearn.model_selection import train_test_split
x, x_val, y, y_val = train_test_split(X, Y, test_size=0.33, random_state=42)

In [9]:
x

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [6]:
x.shape, y.shape, x_val.shape, y_val.shape

((100, 4), (100,), (50, 4), (50,))

In [7]:
x.shape, y.shape

((100, 4), (100,))

In [8]:
x_train = x.reshape(-1, x.shape[1]).astype('float32')
y_train = y

x_val = x_val.reshape(-1, x_val.shape[1]).astype('float32')
y_val = y_val

In [8]:
x_train.shape

(100, 4)

In [9]:
x_val = torch.from_numpy(x_val)
y_val = torch.from_numpy(y_val)

In [10]:
from torch.utils.data import Dataset, DataLoader
class Data(Dataset):
    def __init__(self):
        self.x=torch.from_numpy(x).type(torch.FloatTensor)
        self.y=torch.from_numpy(y).type(torch.LongTensor)
        self.len=self.x.shape[0]
    def __getitem__(self,index):
        return self.x[index], self.y[index]
    def __len__(self):
        return self.len

In [11]:
data_set=Data()

In [12]:
trainloader=DataLoader(dataset=data_set,batch_size=10)

In [13]:
data_set.x[0:10]

tensor([[5.7000, 2.9000, 4.2000, 1.3000],
        [7.6000, 3.0000, 6.6000, 2.1000],
        [5.6000, 3.0000, 4.5000, 1.5000],
        [5.1000, 3.5000, 1.4000, 0.2000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [5.0000, 3.5000, 1.3000, 0.3000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [5.0000, 2.0000, 3.5000, 1.0000]])

In [14]:
data_set.y[0:10]

tensor([1, 2, 1, 0, 2, 1, 0, 0, 0, 1])

In [15]:
data_set.x.shape, data_set.y.shape

(torch.Size([100, 4]), torch.Size([100]))

In [16]:
class Net(nn.Module):
    def __init__(self,in_size,n_hidden1,n_hidden2,out_size,p=0):

        super(Net,self).__init__()
        self.drop=nn.Dropout(p=p)
        self.linear1=nn.Linear(in_size,n_hidden1)
        nn.init.kaiming_uniform_(self.linear1.weight,nonlinearity='relu')
        self.linear2=nn.Linear(n_hidden1,n_hidden2)
        nn.init.kaiming_uniform_(self.linear1.weight,nonlinearity='relu')
        self.linear3=nn.Linear(n_hidden2,n_hidden2)
        nn.init.kaiming_uniform_(self.linear3.weight,nonlinearity='relu')
        self.linear4=nn.Linear(n_hidden2,out_size)

    def forward(self,x):
        x=F.relu(self.linear1(x))
        x=self.drop(x)
        x=F.relu(self.linear2(x))
        x=self.drop(x)
        x=F.relu(self.linear3(x))
        x=self.drop(x)
        x=self.linear4(x)
        return x

In [17]:
model=Net(4,10,5,3)
model_drop=Net(4,10,5,3,p=0.2)
model_drop

Net(
  (drop): Dropout(p=0.2, inplace=False)
  (linear1): Linear(in_features=4, out_features=10, bias=True)
  (linear2): Linear(in_features=10, out_features=5, bias=True)
  (linear3): Linear(in_features=5, out_features=5, bias=True)
  (linear4): Linear(in_features=5, out_features=3, bias=True)
)

In [18]:
model_drop.train()

Net(
  (drop): Dropout(p=0.2, inplace=False)
  (linear1): Linear(in_features=4, out_features=10, bias=True)
  (linear2): Linear(in_features=10, out_features=5, bias=True)
  (linear3): Linear(in_features=5, out_features=5, bias=True)
  (linear4): Linear(in_features=5, out_features=3, bias=True)
)

In [19]:
optimizer_ofit = torch.optim.Adam(model.parameters(), lr=0.01)
optimizer_drop = torch.optim.Adam(model_drop.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()

In [20]:
LOSS={}
LOSS['training data no dropout']=[]
LOSS['validation data no dropout']=[]
LOSS['training data dropout']=[]
LOSS['validation data dropout']=[]

In [21]:
n_epochs=20

for epoch in range(n_epochs):
    for x, y in trainloader:
        #make a prediction for both models
        yhat = model(data_set.x)
        yhat_drop = model_drop(data_set.x)
        #calculate the lossf or both models
        loss = criterion(yhat, data_set.y)
        loss_drop = criterion(yhat_drop, data_set.y)

        #store the loss for  both the training and validation  data for both models
        LOSS['training data no dropout'].append(loss.item())
        LOSS['training data dropout'].append(loss_drop.item())
        model_drop.eval()
        model_drop.train()

        #clear gradient
        optimizer_ofit.zero_grad()
        optimizer_drop.zero_grad()
        #Backward pass: compute gradient of the loss with respect to all the learnable parameters
        loss.backward()
        loss_drop.backward()
        #the step function on an Optimizer makes an update to its parameters
        optimizer_ofit.step()
        optimizer_drop.step()

        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 1.0914734601974487
epoch 0, loss 1.0669976472854614
epoch 0, loss 1.0420163869857788
epoch 0, loss 1.0222561359405518
epoch 0, loss 1.0018383264541626
epoch 0, loss 0.9818649291992188
epoch 0, loss 0.9609546661376953
epoch 0, loss 0.9406586289405823
epoch 0, loss 0.9200198650360107
epoch 0, loss 0.899290919303894
epoch 1, loss 0.8782057762145996
epoch 1, loss 0.8507199883460999
epoch 1, loss 0.7923216223716736
epoch 1, loss 0.7322948575019836
epoch 1, loss 0.690931499004364
epoch 1, loss 0.6642774939537048
epoch 1, loss 0.6351869106292725
epoch 1, loss 0.5968371629714966
epoch 1, loss 0.5593653321266174
epoch 1, loss 0.5329017043113708
epoch 2, loss 0.5175607204437256
epoch 2, loss 0.501884400844574
epoch 2, loss 0.4796796143054962
epoch 2, loss 0.4546179473400116
epoch 2, loss 0.4339020550251007
epoch 2, loss 0.4209747016429901
epoch 2, loss 0.411245197057724
epoch 2, loss 0.39793747663497925
epoch 2, loss 0.380657434463501
epoch 2, loss 0.3647836744785309
epoch 3, loss 

In [22]:
yhat[0:10]

tensor([[ -4.4846,   4.4415,  -3.3953],
        [-11.1101,   2.9503,  12.9989],
        [ -5.7360,   3.8979,   0.4017],
        [  6.8188,  -2.4858, -28.1649],
        [-11.1732,   2.9544,  13.1063],
        [ -3.6291,   4.8577,  -6.1103],
        [  6.7986,  -2.4764, -28.0897],
        [  6.6763,  -2.4190, -27.6346],
        [  6.3119,  -1.9902, -27.1213],
        [ -3.6219,   3.9316,  -3.6468]], grad_fn=<SliceBackward0>)

In [23]:
torch.max(yhat.data,1)

torch.return_types.max(
values=tensor([ 4.4415, 12.9989,  3.8979,  6.8188, 13.1063,  4.8577,  6.7986,  6.6763,
         6.3119,  3.9316,  4.7880,  5.9321,  6.0858,  5.7469,  4.1421,  6.6762,
         4.6981, 10.0792,  6.1575,  4.7957, 10.2836,  7.7861,  3.6610,  9.0621,
         4.5921,  3.7217,  9.4765,  3.8042,  7.0484,  4.4213,  8.1672,  6.5531,
         6.5524,  4.3846,  4.1333,  6.2401, 10.3057,  6.6011,  5.9317,  3.6615,
         4.7354, 10.0186,  5.6290,  7.4328, 10.8365,  4.0155,  5.7214,  5.9982,
         6.6473,  6.5896,  6.0149,  6.7041,  5.8640,  3.6410, 10.8774,  6.2334,
         8.2463, 12.4928,  6.2799,  4.2111,  4.3932,  3.9317,  5.3209,  9.0820,
         7.0100,  6.6111,  4.4214,  6.3670,  5.1822,  3.8978,  4.4031,  5.0193,
         4.8890,  3.9266,  7.1122,  4.5454,  9.9376,  8.5033,  6.7327,  4.4388,
        11.7583,  4.4278,  6.8785, 11.2616,  6.1922,  4.8035,  9.5156,  8.7853,
         4.4223,  6.7606,  4.1636,  4.9719,  8.7589,  6.2134,  6.7856,  4.8611,
         

In [24]:
y

tensor([1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [25]:
z = model(x_val)
z_dropout = model_drop(x_val)

In [26]:
_,yhat=torch.max(z.data,1)
yhat[0:20]

tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2])

In [ ]:
_,yhat_dropout=torch.max(z_dropout.data,1)
yhat_dropout[0:20]

In [ ]:
y_val[0:20]

In [ ]:
# Making the Confusion Matrix
eval_matrix = (pd.crosstab(y_val, yhat))
print(eval_matrix)

In [ ]:
# Making the Confusion Matrix
eval_matrix_dropout = (pd.crosstab(y_val, yhat_dropout))
print(eval_matrix_dropout)

In [ ]:
(eval_matrix[0][0]+eval_matrix[1][1]+eval_matrix[2][2])/y_val.shape[0]

In [ ]:
(eval_matrix_dropout[0][0]+eval_matrix_dropout[1][1]+eval_matrix_dropout[2][2])/y_val.shape[0]